### ISSUE TITLE
unexpected deletion behavior when multiple tags have same manifest digest

### ISSUE THREAD

**Issue by Valodim** [moritzrinow/regmaid#2]
Hey there,

first off, thanks for regmaid! It was surprisingly hard finding anything that would just perform simple cleanup of docker registries, that wasn't also a loose collection of bash scripts :)

While testing regmaid, we found a bug. When considering tags for deletion in a simple "keep: 2" policy, if there are three tags resolving to the same manifest digest, regmaid will decide to delete one of them, by that tag's manifest digest. This will effectively delete all three tags, since the manifest digest is shared.

From our test, this seems to only affect `application/vnd.docker.distribution.manifest.v2+json` manifests

### reproducer

apologies for the image size, any `application/vnd.docker.distribution.manifest.v2+json` will do but I couldn't find one quickly :)

```sh
# copy same image with three different tags
regctl image copy registry.heylogin.app/backup:latest registry.local/test:a
regctl image copy registry.heylogin.app/backup:latest registry.local/test:b
regctl image copy registry.heylogin.app/backup:latest registry.local/test:c

# run regmaid with a simple "keep: 2" config, see below
regmaid --yes

# returns empty list
regctl tag list registry.local/test
``` 

```yaml
policies:
- keep: 2
  match: '*'
  name: keep only last two tags
  registry: registry
  repository: '*'
registries:
- host: registry.local
  name: registry
```
